### ISSUE TITLE
Seriously odd layout...

### ISSUE THREAD

**Issue by isiahmeadows** [bterlson/ecmarkup#110]
Here's what I'm seeing (no console errors or anything, BTW), at least on [TC39's SIMD spec](https://tc39.github.io/ecmascript_simd/), among others:

![screenshot from 2016-11-27 04-11-56](https://cloud.githubusercontent.com/assets/4483844/20647048/abdc8c74-b457-11e6-977c-21a2a06713da.png)

This is with Chrome on Ubuntu GNOME 64-bit. And it didn't start until probably the last week or so.

**Comment by lars-t-hansen** [comment]
I'm having similar problems with a locally formatted copy of the shared memory draft, this is in Firefox on Mac OS X.  (In addition, trying to save that draft to a PDF in either Firefox or Chrome results only in the first page being added to the PDF.)

**Comment by bterlson** [comment]
@lars-t-hansen please update your ecmarkup and regenerate your spec. If you don't want to be broken in the future, you should use local css/js rather than hotlinking ecma262's using emu's --css/--js options. What happened is I changed the stylesheet for the main spec and it is no longer compatible with old markup. I'd like to support hot-linking but it doesn't seem realistic to avoid breaking changes (especially for big layout changes like this).
