### ISSUE TITLE
alphanumeric values inside variables?

### ISSUE THREAD

**Issue by caridy** [bterlson/ecmarkup#27]
`_opt_.[[_&lt;key&gt;_]]` is producing `opt_.[[_<key>]]`

**Comment by domenic** [comment]
Should be part of https://github.com/domenic/ecmarkdown/issues/25

**Comment by domenic** [comment]
Can you link to an example of how this should look in the wild? Our current thinking is that variables should not contain special characters like `<` and `>`. This seems like a counterexample.

**Comment by caridy** [comment]
@domenic here is the discussion about `<variables>` https://github.com/tc39/ecma402/pull/19#discussion_r34748525, this is probably specific to 402, which I'm up for changing in the future to align better with other specs.

After talking to @bterlson, he mentioned that alphanumeric values for variables in the way to move forward, in which case we can change 402 to use something like: `_opt_.[[&lt;_key_&gt;]]`

**Comment by bterlson** [comment]
As of latest master, _ will actually accept anything that isn't whitespace or a format token (basically anything lexed as "text"). So the former works in EMD. However, Emu needs to pass innerHTML not textContent otherwise it will see `&lt;key&gt;` as a tag.

IOW, @caridy I think you can continue with the current conventions and I will make EMD and Emu do what you want.

**Comment by domenic** [comment]
Hmm yeah maybe it is not typographically distinct enough but I think just `_opt_.[[_key_]]` (i.e. _opt_.[[_key_]]) is clear enough; no need for `_opt_.[[&lt;_key_&gt;]]` (i.e. no need for _opt_.[[&lt;_key_&gt;]]). Maybe consider than for 402 in the future.

In the meantime I agree that `_opt_.[[&lt;_key_&gt;]]` is the way to go.

**Comment by bterlson** [comment]
Yeah I like `_opt_.[[_key_]]` better too.

**Comment by bterlson** [comment]
Should be fixed in 1.6.
