### ISSUE TITLE
Wide table is inaccessible

### ISSUE THREAD

**Issue by littledan** [bterlson/ecmarkup#63]
Look at this:
http://tc39.github.io/ecmascript_simd/#deserialize-int

In Chrome, I don't get a horizontal scrollbar, and the table is simply inaccessible. Smells like a stylesheet issue.

**Comment by bterlson** [comment]
Hmm, I agree with stylesheet issue (I'll theorize further that its due to improper usage of the overflow property somewhere). But that said, this table seems simply too wide. In the old days it would not fly as it's too wide to fit on a page. We care less about this today but requiring horizontal scrollbars and horizontal scrolling seems unfortunate... Possible to split the columns into two separate tables maybe?

**Comment by littledan** [comment]
Thanks! Yeah maybe it should be done some other way, maybe transposed or with shorter heading text or something. Two tables would seem unfortunate unless there's a clear semantic way of breaking it up that doesn't come to mind immediately to me.

**Comment by bterlson** [comment]
I can't think of something obvious :(
