### ISSUE TITLE
Not escaping characters correctly

### ISSUE THREAD

**Issue by arv** [bterlson/ecmarkup#9]
My input html has

```html
<p>1 &lt; 2</p>
```

and the output ends up being

```html
<p>1 < 2</p>
```

**Comment by bterlson** [comment]
Do you have the latest version installed? Here's what I'm getting:

```html
<!doctype html>
<emu-clause>
  <h1>test</h1>
  <p>Test that a &lt; b escapes properly</p>
  <emu-alg>
    1. a &lt; b
  </emu-alg>
</emu-clause>
```
compiles to

```html
<!doctype html>
<head></head><body><div><h2>Table of Contents</h2><ol class="toc"><li><a href="#"><span class="secnum">1</span> test</a></li></ol></div><emu-clause>
  <h1><span class="secnum">1</span>test</h1>
  <p>Test that a
  &lt; b escapes properly</p>
  <emu-alg><ol>
  <li>a &lt; b</li>
</ol></emu-alg>
</emu-clause>
</body>
```
Which has the proper escaping. In Chrome dev tools it appears the characters are unescaped - perhaps that's the confusion?

**Comment by arv** [comment]
My `&lt;` is not inside an `<emu-alg>`, but inside an `<emu-clause>`

https://github.com/arv/ecmascript-object-observe/blob/master/spec/KeyAlgorithmsAndSemantics.html#L45

http://arv.github.io/ecmascript-object-observe/

```
$0.outerHTML
"<p>An observation is conceptually a tuple:
  <observed object,="" observer="" function,="" accepted="" change="" types="">. Object.observe ensures that this tuple is represented as an observerRecord in the associated Notifier's ChangeObservers list.</observed></p>"
```

**Comment by bterlson** [comment]
I had that above as well, but it turns out the key is if you put spaces before and after your angle bracket it will be escaped...

I guess this is because when processing paragraphs, I loop through each text node and pass its textContent to emd. At this stage I've lost the escaping of element-like things. I then set the innerHTML of a temporary element to this result and loop over the children of this temporary element, appending each in the right place.

I think I can fix this by first cloning the text node and appending it to a temporary div. This will let me call innerHTML on that temporary div, preserving the escapes. Anyone know a better way to do this that doesn't involve a temporary div? Is there any API in the DOM like textContent that returns escapes verbatim?

**Comment by domenic** [comment]
Is there a reason why you can't just pass `pElement.innerHTML` to ecmarkdown?

**Comment by domenic** [comment]
Alternately I think the div trick is equivalent to `htmlEscape(textNode.textContent)`.

**Comment by bterlson** [comment]
The reason I iterate over textNodes not elements is because of the following:

```html
<emu-clause>
  <div>
    text1
    <p>text2</p>
    text3
    <emu-alg>...</emu-alg>
  </div>
</emu-clause>
```
Current algorithm is to loop over all text nodes under an emu-clause that aren't nested inside another emu-clause, emu-alg, pre or code tags. I can't just pass the div element to emd because it will process elements I don't want to pass to emd.paragraph. I could special case p tags I suppose but that doesn't quite solve the problem. So AFAIK I have to iterate over text nodes to pass each to emd.

Where is htmlEscape defined? I don't see it on document or window...

**Comment by arv** [comment]
htmlEscape is not part of the platform. You'll have to write it yourself (or use npm).

**Comment by domenic** [comment]
I meant write your own htmlEscape :). (I, uh, don't know why we don't have one of those baked in.)

I see how making the the floating text nodes work is nice. Hmm. It does sound like this is being used not in the way I intended `emd.paragraph` to be used. So for example it sounds like given

```html
<p>Some emd <ins>some more emd</ins> extra emd</p>
```

this will be converted to

```html
<p>emd("Some emd ")<ins>emd("some more emd")</ins>emd(" extra emd")</p>
```

So you want more, `emd.textFragment`, rather than `emd.paragraph`. In this case I can assume that any EMD you pass me will contain no HTML, and so I can escape any `<`s, `>`s, or `&`s I see.

(An alternative design would be e.g. `<p emd>`, `<whatever emd>`, ... but that doesn't seem author-ergonomic.)

---

Related question: https://github.com/domenic/ecmarkdown/issues/16 proposes converting `<<x>>` to «‍x» for ES List shorthand. It sounds like given the fragment model (instead of the paragraph model I was assuming) this is not feasible. So we should work in that bug to come up with a new shorthand probably.

**Comment by bterlson** [comment]
I would use the textFragment API if it did HTML escaping for me :+1: 

Another alternative is to only process emd in p tags (which I think are not allowed to contain other block level elements). This might be reasonably ergonomic.

So, options are:
1. ecmarkdown implements textFragment that escapes HTML.
2. ecmarkup processes ecmarkdown only in p tags
3. ecmarkup takes care to call escapeHTML or equivalent on the output of emd.paragraph (after stripping off the outer p tags).

I'm personally OK with 2, but otherwise 1 seems like best to me ;) Thoughts @domenic?

**Comment by domenic** [comment]
1 seems good, can do. Probably tonight.

I'm a little worried about the processing model being divergent between `<emu-alg>` (where HTML is allowed by virtue of just passing through `emd.list` without being messed with, with no escaping) and the everywhere else (where HTML is allowed by virtue of `emd.textFragment` never seeing it, and special characters are escaped). But, I don't think users will be able to notice a difference, so it is probably fine...

**Comment by bterlson** [comment]
Processing only p tags would preferve identical models between emu-alg and p tags, but I agree that the current model of processing all text nodes is pretty nice in terms of author ergonomics. I think emd.textFragment would end up just working since the DOM will ensure that the text fragment doesn't contain any html...

I think the only observable thing that could be an issue is that you can't wrap html with emd in paragraphs, eg:

```html
<p>*<i>non-terminal and italic??</i>*</p>
```
but I think that's ok.

**Comment by bterlson** [comment]
This seems to not be an issue any longer.
